# fly.toml file generated for datingapp-chrik on 2023-01-17T23:54:27+01:00

app = "datingapp-chrik"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "christianfe/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySetting__CloudName="dhh2pg3tc"
  CloudinarySetting__ApiKey="361114381184428"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
